version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: "/src/StarOJ/Client"
    schedule:
      interval: daily
    allow:
      - dependency-type: production
    open-pull-requests-limit: 3
  - package-ecosystem: "docker"
    directory: "/src/StarOJ/Server"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
