version: "3.4"

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  judge0server:
    image: registry.cn-hangzhou.aliyuncs.com/stardustdl/judge0:latest
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  judge0workers:
    image: registry.cn-hangzhou.aliyuncs.com/stardustdl/judge0:latest
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  judge0db:
    image: postgres:9.6
    env_file: judge0.conf
    volumes:
      - judge0dbdata:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  judge0redis:
    image: redis:4.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    volumes:
      - judge0redisdata:/data
    <<: *default-logging
    restart: always
  
  client:
    image: registry.cn-hangzhou.aliyuncs.com/stardustdl/staroj:latest
    ports:
      - "7000:80"
    environment:
      - ConnectionStrings:IdentityConnection=Server=db;User=sa;Password=MyPassword001;Database=api_identity;
      - ConnectionStrings:DefaultConnection=Server=db;User=sa;Password=MyPassword001;Database=api_default;
      - IdentityServer:Options:PublicOrigin=http://localhost:7000
    # volumes:
      # - ./client/appsettings.json:/app/appsettings.json
    depends_on:
      - db
  db:
    image: registry.cn-hangzhou.aliyuncs.com/stardustdl/mssql:latest
    environment:
      - SA_PASSWORD=MyPassword001
      - ACCEPT_EULA=Y
    volumes:
      - data:/var/opt/mssql
    ports:
      - "1433:1433"
  
volumes:
  data:
  judge0redisdata:
  judge0dbdata: