version: "3.4"

services:
  client:
    image: stardustdl/staroj:latest
    ports:
      - "6000:80"
    volumes:
      - ./client/appsettings.json:/app/appsettings.json
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=MyPassword001
      - ACCEPT_EULA=Y
    volumes:
      - data:/var/opt/mssql
    ports:
      - "1433:1433"
volumes:
  data: